[package]
name = "wasm_vrf_worker"
version = "0.1.0"
edition = "2021"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
base64ct = { version = "1.6", features = ["alloc"] }
bincode = "1.3"
chacha20poly1305 = "0.10"
console_error_panic_hook = "0.1"
ed25519-dalek = "2.0"
getrandom = { version = "0.2", features = ["js"] }
hkdf = "0.12"
js-sys = "0.3"
rand_core = "0.6"
sha2 = "0.10"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
sra-wasm = "0.1.0"
wasm-bindgen = "0.2"
zeroize = { version = "1.7", features = ["derive"] }
# VRF and cryptography
vrf-wasm = { version = "0.8.2", features = ["browser"] }
# Logging dependencies
log = "0.4"
wasm-logger = "0.2"


[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]