name = "w3a-relay"
main = "src/worker.ts"
compatibility_date = "2024-09-24"
compatibility_flags = ["nodejs_compat"]

[wasm_modules]
SIGNER_WASM = "../../passkey-sdk/src/wasm_signer_worker/pkg/wasm_signer_worker_bg.wasm"

# Default inactive; add a cron schedule here when you enable rotation or heartbeats.
[triggers]
crons = []

[vars]
RELAYER_ACCOUNT_ID = "w3a-relayer.testnet"
NEAR_RPC_URL = "https://test.rpc.fastnear.com"
NETWORK_ID = "testnet"
# Align with src/worker.ts Env: WEBAUTHN_CONTRACT_ID
WEBAUTHN_CONTRACT_ID = "web3-authn-v5.testnet"
ACCOUNT_INITIAL_BALANCE = "30000000000000000000000"
CREATE_ACCOUNT_AND_REGISTER_GAS = "85000000000000"

# Secrets are NOT defined here. Set them via Wrangler secrets (they persist across deploys):
#   wrangler secret put RELAYER_PRIVATE_KEY
#   wrangler secret put SHAMIR_P_B64U
#   wrangler secret put SHAMIR_E_S_B64U
#   wrangler secret put SHAMIR_D_S_B64U
# Required at runtime by src/worker.ts

# Optional CORS
EXPECTED_ORIGIN = "https://tatchi.xyz/"
EXPECTED_WALLET_ORIGIN = "https://wallet.tatchi.xyz"

# Optional: explicitly enable cron and rotation (defaults to disabled)
# ENABLE_ROTATION = "0"

# Observability (Workers Logs). Requires appropriate Cloudflare plan.
[observability.logs]
enabled = true
